### ISSUE TITLE
[Feature Request] Adding Visualizations for better understanding of Shortest Path Graph Algorithms

### ISSUE THREAD

**Issue by J-B-Mugundh** [Ajay-Dhangar/algo#460]
### Is your feature request related to a problem? Please describe.

Currently, the Shortest Path Graph Algorithms section (Not just this section) primarily contains theoretical content and code implementations, which can make it challenging for users to fully grasp the concepts. Users, especially beginners may struggle to visualize how the algorithms work in practice, leading to potential misunderstandings or difficulties in applying the algorithms to real-world problems.

### Describe the solution you'd like
I propose incorporating visualizations for each of the Shortest Path Graph Algorithms using Mermaid diagrams and Docusaurus

### Describe alternatives you've considered
.

### Additional context
.

### Screenshots of samples
![image](https://github.com/user-attachments/assets/fb9d3e00-d7cf-4e00-aec9-4952e6ef7fa2)
![image](https://github.com/user-attachments/assets/44a6365d-3932-4a69-bf07-8ac1f041db0c)
![image](https://github.com/user-attachments/assets/e8cf59d7-65a6-4c61-b211-4e48c9f48342)
![image](https://github.com/user-attachments/assets/e89804fe-f9ff-4bb5-bc0f-9d756c5bf744)
![image](https://github.com/user-attachments/assets/96ae04ea-4fd7-4f03-b079-f88f248b4798)
![image](https://github.com/user-attachments/assets/77827c75-5a57-40f4-8b6b-ed96397cc3ad)

---

**Would you like to work on this feature?**  
- [x] Yes  
- [ ] No

**Comment by ajay-dhangar** [comment]
@J-B-Mugundh, can you add a visualization like https://ajay-dhangar.github.io/algo/docs/basic-dsa/array/arrays-in-dsa#visualizations-of-arrays-in-data-structures-and-algorithms-dsa and code like https://github.com/ajay-dhangar/algo/tree/main/src/components/DSA/arrays? If you can do that, I'll assign you level 3. For now, I'll assign you level 2.

**Comment by J-B-Mugundh** [comment]
@ajay-dhangar Could u elaborate? I could add the code by creating a folder let's say GraphVisualizer and inside that folder, i'll have a file called index.tsx . Then, i'll mention as <GraphVisualizer/> in the md code? Is that it?

**Comment by J-B-Mugundh** [comment]
@ajay-dhangar I'm getting some import error

Expected component `DijkstraVisualizations` to be defined: you likely forgot to import, pass, or provide it.
    at _missingMdxReference (webpack-internal:///./docs/graphs/shortest-path-algorithms/dijkstra-algorithm.md:185:9)
    at _createMdxContent (webpack-internal:///./docs/graphs/shortest-path-algorithms/dijkstra-algorithm.md:111:32)
    at MDXContent (webpack-internal:///./docs/graphs/shortest-path-algorithms/dijkstra-algorithm.md:182:8)
    at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:15486:18)
    at mountIndeterminateComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20098:13)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21621:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4213:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4277:31)
    at beginWork$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:27485:7)
    
    
 I've added it like this
 
 
![image](https://github.com/user-attachments/assets/d99ec1c6-7602-4b63-8844-23a3899cc3f1)

And also, I've imported the same in MDXComponents.js

![image](https://github.com/user-attachments/assets/b6204d5b-1567-4727-92ec-407a47ba292b)

Could u please help me on this?

**Comment by J-B-Mugundh** [comment]
@ajay-dhangar I've resolved the issues and implemented like this.. is it fine?

https://drive.google.com/file/d/1DE9iJOQCstLYPAmWNUsBlDlub1oypFv9/view?usp=sharing
